---
# ansible-playbook sample

# usage: ansible-playbook deploy.yaml --
# example: in jenkins | ansible-playbook /etc/ansible/www-sre/deploy.nginx.yaml --extra-vars "work_space=${WORKSPACE}"

- hosts: www-lbhost1-java
  vars:  #定义变量
    work_space: /data/home/jenkins/.jenkins/workspace/www-job-name
    become: yes
    become_user: root

  tasks:

  - name: sync nginx conf
    synchronize:
      src: "{{work_space}}/nginx/"
      dest: /data/appdatas/nginx/
      delete: yes

  - name: nginx check
    shell: nginx -t

  - name: nginx reload
    # shell: service nginx reload
    service: name=nginx state=reloaded
