# docker network create app-network
services:
  redis-7:
    image: redis:7.2.4
    container_name: app-redis  # 关键：其他容器将通过这个名字访问它
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /data/appdatas/redis:/data:rw
    command: redis-server --appendonly yes # --requirepass "YourSecurePassword" # 强烈建议加密码
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 10s
      timeout: 3s
      retries: 3

networks:
  app-network:
    external: true  # 声明这是个外部已存在的网络